server:
  port: ${PORT:8443}
  #address: local.localhost
  servlet:
    contextPath: /
  ssl:
    enabled: true
    #key-alias: local.localhost
    key-store-type: PKCS12
    key-store: config/ssl/key-store.pfx
    key-store-password: storepass
    trust-store-type: PKCS12
    trust-store: config/ssl/trust-store.pfx
    trust-store-password: storepass
    client-auth: want
app:
  route:
    api: ${API:/api/v1}
  proxy:
    enabled: false
    host: my.proxy
    port: 80
  certificates-enable:
          
security:
  headers:
    hsts: NONE

spring:
  #main:
  #  web-application-type: reactive
  messages:
    basename: i18n/messages
    encoding: UTF-8
  application:
    name: checkout-payment-api
  # En desarrollo para pruebas
  webflux:
    static-path-pattern: classpath:/static/**
  # Database
  sql:
    init:
      mode: embedded
      platform: ${DATASOURCE_PLATFORM:POSTGRESQL}
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/payment_r2dbc
    username: payment
    password: payment
    initialization-mode: always
    pool:
      enabled: true
      initial-size: 5
      max-size: 10

# Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: loggers
    #beans:
    #  cache:
    #    time-to-live: 10s
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export: 
        enabled: true
  server:
    port: 8091
    address: 127.0.0.1
    base-path: /
  security:
    enabled: false

# https://www.baeldung.com/spring-boot-info-actuator-custom
info:
  app:
    name: checkout-payment-api
  environment: desarrollo
  
logging:
  file: logs/checkout-payment-api.log
  level:
    root: INFO
